spring:
  datasource:
    url: jdbc:postgresql:robio-app
    username: robio
    password: robio
    driverClassName: org.postgresql.Driver
springdoc:
  swagger-ui:
    operationsSorter: alpha
robio:
  ftl:
    persistence:
      schema: ftl
