spring:
  datasource:
    url: jdbc:postgresql:robio-app
    username: robio
    password: robio
    driverClassName: org.postgresql.Driver
springdoc:
  swagger-ui:
    operationsSorter: alpha
robio:
  auth:
    core:
      scheduler:
        remove-expired-refresh-tokens:
          cron: 0 0 0 * * *
      token:
        key-secret: PV)GbnDpdDQ^uM3
        issuer: http://localhost:8080/auth
        refresh:
          validity-duration: 3d
        access:
          validity-duration: 15m
    persistence:
      schema: auth
      flyway:
        enabled: true
  ftl:
    persistence:
      schema: ftl
      flyway:
        enabled: true
